repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7  # Must match pyproject.toml
    hooks:
      - id: ruff-format
      - id: ruff-check

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0  # Must match pyproject.toml
    hooks:
      - id: mypy
        additional_dependencies:  # Must match pyproject.toml
          - attrs>=21.3.0
          - types-panda3d==0.4.1

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
